# For labels
labels:
  - name: bug-report
    # Add `bug` label if issue contains the word `Bug` or `bug`; Remove if not
    content: bug
    regexes:
      - '[Bb]ug'
  - name: enhancement
    content: enhancement
    # Add `enhancement` label if issue match all of the regexes; Remove if not; Skip if the label `bug` have been added;
    regexes:
      - '[Ee]nhancement'
      - '[Ff]eature [Rr]equest'
      - '功能请求'
      - '新功能'
      - '(能|可以?|行)不(行|能|可以)'
    skip-if:
      - bug-report
  - name: UI
    content: UI
    regexes:
      - '[Uu][Ii]'
      - '界面'
  - name: momotalk
    content: "module: momotalk"
    regexes:
      - '([Mm][Oo]){2}\s{0,}[Tt][Aa][Ll][Kk]'
  - name: story
    content: "module: story"
    regexes:
      - '([Ss][Tt][Oo][Rr][Yy])'
      - '故事|剧情'
  - name: safari
    content: safari
    regexes:
      - '[Ss][Aa][Ff][Aa][Rr][Ii]'
  - name: chrome
    content: chrome
    regexes:
      - '[Cc][Hh][Rr][Oo][Mm][Ee]'
      - '谷歌'
  - name: firefox
    content: firefox
    regexes:
      - '[Ff][Ii][Rr][Ee][Ff][Oo][Xx]'
      - '火狐'
# For comments
comments:
  - name: Log upload failed
    regexes:
      - '\[Uploading asst(?:.bak|)(?: - 副本|)(?:.log|)(?:.zip|)…\]\(\)'
    content:
      "你的日志没有上传成功，请重新上传。\n\n\
      Your log did not upload successfully, please re-upload it."
    mode: add
  - name: Upload failed
    regexes:
      - "^[^`]*(`[^`]+`[^`]*)*\\[Uploading[^\\]]*…\\]\\(\\)"
    content:
      "你有一些文件没有上传成功，请重新上传。\n\n\
      You have some files that did not upload successfully, please re-upload them."
    mode: add
    skip-if:
      - "Log upload failed"
